### ISSUE TITLE
Invalid Double Issue

### ISSUE THREAD

**Issue by neilkerman** [hemanthrajv/flutter_3d_obj#18]
Hi, I've encountered the following issue. Please check:

My Code:
`@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Object3D(
            size: const Size(400.0, 400.0),
            path: 'assets/banana_plant/banana_plant.obj',
            asset: true),
      ),
    );
  }`

The Exception:

`I/flutter (28517): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (28517): The following FormatException was thrown during paint():
I/flutter (28517): Invalid double
I/flutter (28517): 
I/flutter (28517): The relevant error-causing widget was:
I/flutter (28517):   CustomPaint
I/flutter (28517):   file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_3d_obj-0.0.6/lib/flutter_3d_obj.dart:118:18
I/flutter (28517):
I/flutter (28517): When the exception was thrown, this was the stack:
I/flutter (28517): #0      double.parse (dart:core-patch/double_patch.dart:112:28)
I/flutter (28517): #1      _ObjectPainter._parseObjString.<anonymous closure> (package:flutter_3d_obj/flutter_3d_obj.dart:181:37)
I/flutter (28517): #2      List.forEach (dart:core-patch/growable_array.dart:282:8)
I/flutter (28517): #3      _ObjectPainter._parseObjString (package:flutter_3d_obj/flutter_3d_obj.dart:174:11)
I/flutter (28517): #4      _ObjectPainter.paint (package:flutter_3d_obj/flutter_3d_obj.dart:307:22)
I/flutter (28517): #5      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:531:13)
I/flutter (28517): #6      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:572:7)
I/flutter (28517): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
I/flutter (28517): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (28517): #9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
I/flutter (28517): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
I/flutter (28517): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (28517): #12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
I/flutter (28517): #13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
I/flutter (28517): #14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (28517): #15     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (28517): #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
I/flutter (28517): #17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (28517): #18     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2515:15)
I/flutter (28517): #19     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:404:5)
I/flutter (28517): #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
I/flutter (28517): #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (28517): #22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
I/flutter (28517): #23     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:531:11)
I/flutter (28517): #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
I/flutter (28517): #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (28517): #26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
I/flutter (28517): #27     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:391:12)
I/flutter (28517): #28     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1800:15)
I/flutter (28517): #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
I/flutter (28517): #30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (28517): #31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
I/flutter (28517): #32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
I/flutter (28517): #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (28517): #34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:15)
I/flutter (28517): #35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
I/flutter (28517): #36     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter (28517): #37     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (28517): #38     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:980:29)
I/flutter (28517): #39     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
I/flutter (28517): #40     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
I/flutter (28517): #41     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (28517): #42     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (28517): #43     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (28517): #44     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (28517): #48     _invoke (dart:ui/hooks.dart:261:10)
I/flutter (28517): #49     _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (28517): (elided 3 frames from dart:async)
I/flutter (28517):
I/flutter (28517): The following RenderObject was being processed when the exception was fired: RenderCustomPaint#128cb relayoutBoundary=up4:
I/flutter (28517):   creator: CustomPaint ← _PointerListener ← Listener ← _GestureSemantics ← RawGestureDetector ←
I/flutter (28517):     GestureDetector ← Object3D ← Center ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>]
I/flutter (28517):     ← CustomMultiChildLayout ← ⋯
I/flutter (28517):   parentData: <none> (can use size)
I/flutter (28517):   constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=785.5)
I/flutter (28517):   size: Size(392.7, 400.0)
I/flutter (28517): This RenderObject has no descendants.
I/flutter (28517): ════════════════════════════════════════════════════════════════════════════════════════════════════`

**Comment by leostelon** [comment]
Even I have this issue.

**Comment by Shockerex** [comment]
I got this Issue too.

**Comment by anirudhsharma392** [comment]
Did you guys find out any solution to it ?
